### ISSUE TITLE
domain upload.wikimedia.org is blocked by ddg hostlist.

### ISSUE THREAD

**Issue by caminsha** [blokadaorg/blokadaorg.github.io#65]
When using the DDG Tracker Radar host list then the domain _upload.wikimedia.org_ is also part of the blocklist as you can see below:

```bash
$ curl -sL https://blokada.org/blocklists/ddgtrackerradar/standard/hosts.txt | grep wikimedia
upload.wikimedia.org
$ 
```

I saw that blocking this domain will not load the images in an article.

So in my opinion there are two possibilities to prevent that this domain is blocked.

1. add a whitelist entry in [this](https://github.com/blokadaorg/blokadaorg.github.io/blob/master/scripts/whitelist) file
2. add the category "Non-Tracking" to the whitelisted categories in the [script](https://github.com/blokadaorg/blokadaorg.github.io/blob/master/scripts/ddg.py)

The domains which have the category "Non-Tracking" are listed below. The domains are taken directly from the duckduckgo [repository](https://github.com/duckduckgo/tracker-radar)

```bash
$ grep -inR "Non-Tracking" domains/
domains/intercomcdn.com.json:124:        "Non-Tracking"
domains/wikimedia.org.json:86:        "Non-Tracking"
domains/dmca.com.json:33:        "Non-Tracking"
domains/cookiebot.com.json:109:        "Non-Tracking"
domains/duckduckgo.com.json:30:        "Non-Tracking"
domains/onetrust.com.json:475:        "Non-Tracking"
domains/wikipedia.org.json:35:        "Non-Tracking"
domains/cookielaw.org.json:946:        "Non-Tracking"
domains/consensu.org.json:989:        "Non-Tracking"
domains/creativecommons.org.json:148:        "Non-Tracking"
domains/github.io.json:129:        "Non-Tracking"
domains/arcgis.com.json:282:        "Non-Tracking"
domains/mediawiki.org.json:44:        "Non-Tracking"
domains/polyfill.io.json:51:        "Non-Tracking"
domains/iubenda.com.json:288:        "Non-Tracking"
$ 
```

As I don't know what these domains are all used for I don't know which possibility is the better one.

**Comment by kar** [comment]
Very good find! I just pushed the suggested change. https://github.com/blokadaorg/blokadaorg.github.io/commit/ddf0231c73e2ea4fc97abf0c52ee510f2b6527d0
