### ISSUE TITLE
domain github.githubassets.com is blocked by ddg hostlist

### ISSUE THREAD

**Issue by yokoffing** [blokadaorg/blokadaorg.github.io#71]
I am using `https://blokada.org/blocklists/ddgtrackerradar/standard/hosts.txt` as a custom list in uBlock Origin.

![Screenshot 2021-03-15 203019](https://user-images.githubusercontent.com/11689349/111238380-5c675d80-85cd-11eb-89d5-b5c1e30d5561.jpg)

The domain `github.githubassets.com` is part of the blocklist and completely breaks Github.

**Comment by yokoffing** [comment]
Just found another: `eadn-wc03-196922.nxedge.io` completely breaks `https://www.psypost.org/`.

**Comment by kar** [comment]
Thanks for the report, whitelisted.
